# Site configuration
title: "dvdhrm"
name: "Ponyhof"
description: "Dysfunctional Programming"
author: "David Rheinsberg"

# Resource configuration
avatar: "images/dvdhrm.png"
avatar_border: true
favicon: "images/dvdhrm.ico"
url: "https://dvdhrm.github.io"

# Media handles
media:
  email: "david.rheinsberg@gmail.com"
  github: "dvdhrm"
  rss: "feed.xml"

# Define default layouts for each page type
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:month/:day/:title/"

#
# External plugins:
#  - jekyll-sitemap: This creates a sitemap.xml for us, allowing easier
#                    indexing of the entire website.
#
plugins:
  - jekyll-sitemap
