# Site configuration
title: "dvdhrm"
name: "Ponyhof"
description: "Dysfunctional Programming"
author: "David Rheinsberg"

# Resource configuration
avatar: "images/dvdhrm.png"
avatar_border: true
favicon: "images/dvdhrm.ico"
url: "https://dvdhrm.github.io"

# Media handles
media:
  email: "david.rheinsberg@gmail.com"
  github: "dvdhrm"
  rss: "feed.xml"
  twitter: "dvdhrm"

#
# Remaining Setup
#

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:month/:day/:title/"

plugins:
  - jekyll-sitemap
